package dev.capstan.policy;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class PolicyConfig {

    private static final Logger log = LoggerFactory.getLogger(PolicyConfig.class);

    /**
     * Copy generation is opt-in and off by default.
     *
     * <p>Not a technical limitation — a free-tier day is 500 requests, a ten-seed
     * backtest already spends ~350 on diagnosis, and generating copy for every
     * nudge across ten runs would exhaust the rest on text the backtest never
     * scores. The template path uses the same validator, so the only thing lost
     * in a backtest is phrasing.
     */
    @Bean
    CopyWriter copyWriter(
            @Value("${capstan.llm.gemini.api-key:}") String apiKey,
            @Value("${capstan.llm.gemini.model:gemini-flash-lite-latest}") String model,
            @Value("${capstan.llm.timeout-ms:30000}") long timeoutMillis,
            @Value("${capstan.copy.generate:false}") boolean generate) {

        if (!generate || apiKey == null || apiKey.isBlank()) {
            log.info("Customer copy: templates only ({})",
                    generate ? "no credentials configured" : "capstan.copy.generate=false");
            return new CopyWriter.Templates();
        }
        log.info("Customer copy: generated by {}, validated before send", model);
        return new CopyWriter.Gemini(apiKey, model, timeoutMillis);
    }
}
